name: Lint

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g
    - run: npm install -g mocha @babel/cli @babel/core @babel/node @babel/preset-env @babel/register
    - run: npm install
    - name: Use lint
      run: npm run checkdev
